pub mod access_control_regression_test;
pub mod admin_test;
pub mod test_helpers;
pub mod analytics_test;
pub mod arithmetic_safety_test;
pub mod asset_config_test;
pub mod config_test;
pub mod deploy_test;
pub mod edge_cases_test;
pub mod events_test;
pub mod integration_test;
pub mod interest_accrual_test;
pub mod interest_rate_test;
pub mod intents_test;
pub mod liquidate_test;
pub mod oracle_test;
pub mod pause_test;
pub mod rate_limiter_test;
pub mod risk_params_test;
pub mod security_test;
pub mod test;
pub mod withdraw_test;
// Cross-asset tests disabled - contract methods not yet implemented
pub mod views_test;
// Cross-asset tests re-enabled when contract exposes full CA API (try_* return Result; get_user_asset_position; try_ca_repay_debt)
// pub mod test_cross_asset;
pub mod bridge_test;
pub mod recovery_test;
pub mod multisig_test;
pub mod multisig_governance_execution_test;
pub mod cross_contract_test;
pub mod timelock_test;
pub mod input_length_test;
